# grades

In [1]:
from pathlib import Path
import pandas as pd

In [2]:
GRADES_DIR = Path.cwd().parent / "data" / "grades"
SCORES_PATH = GRADES_DIR / "scores.tsv"
STUDENTS_PATH = GRADES_DIR / "students.tsv"
print(f"Scores are here: {SCORES_PATH}")
print(f"Students are here: {STUDENTS_PATH}")

Scores are here: /Users/void/code/chengdu/science/data/grades/scores.tsv
Students are here: /Users/void/code/chengdu/science/data/grades/students.tsv

In [3]:
students = (
    pd.read_csv(STUDENTS_PATH, sep="\t")
    .set_index('id_student')
    .sort_index()
)
students

           name_family      name_given country_code
id_student
104           Kennerly          Samuel           US
329           Torvalds  Linus Benedict           FI
466           Lovelace      Agusta Ada           UK
777           Sweigart              Al           CA
781             Hopper           Grace           US
926         van Rossum           Guido           NL
974            Babbage         Charles           UK

In [4]:
scores = (
    pd.read_csv(SCORES_PATH, sep="\t")
    .set_index('id_student')
    .sort_index()
)
scores

            attendance  homework  project   exam
id_student
104               80.0      40.0       20   10.0
329                NaN       NaN       91    NaN
466              100.0     100.0      100  100.0
777               42.0      42.0       42   42.0
781               90.0      86.0       90   85.0
926               50.0       NaN       89    0.0
974               60.0      70.0       80   90.0